package domain;

public enum CreditType {
    Billedkunstner,
    BilledOgLydRedigering,
    Casting,
    Colourgrading,
    Dirigenter,
    Drone,
    Dukkefører,
    Dukkeskaber,
    Fortæller,
    Fotograf,
    Forlæg,
    GrafiskDesigner,
    Indtaler,
    Kapelmester,
    Klipper,
    Programkoncept,
    Konsulent,
    Kor,
    Koreografi,
    LydEllerTonemester,
    Ledredigering,
    Lys,
    Medvirkende,
    Musiker,
    MusikalskArrangement,
    OrkesterEllerBand,
    Oversætter,
    Producent,
    Producer,
    ProduktionskoordinatorEllerProduktionsleder,
    Programansvarlig,
    RedaktionEllerTilrettelæggelse,
    Redaktør,
    Rekvisitør,
    Scenograf,
    ScripterEllerProducerassistent,
    SpecialEffects,
    Sponsor,
    TegnefilmEllerAnimation,
    Tekster,
    TekstOgMusik,
    UhonoreretEkstraordinærIndsats

}
